name: install-test
on: [push]

jobs:

  install-test:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository and submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install dependencies
        run: pip3 install -r $GITHUB_WORKSPACE/requirements.txt

      - name: Build and install package
        run: |
          python3 -m build
          pip3 install $GITHUB_WORKSPACE

      - name: Run tests
        run: python3 test/test.py
